apiVersion: apps/v1
kind: Deployment
metadata:
  name: m07-web
  labels:
    app: m07-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: m07-web
  template:
    metadata:
      labels:
        app: m07-web
    spec:
      containers:
        - name: m07-web
          image: ghcr.io/dftuil/m07-web:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
