apiVersion: v1
kind: Service
metadata:
  name: m07-web
  labels:
    app: m07-web
spec:
  type: NodePort
  selector:
    app: m07-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30087
